import { readFileSync, writeFileSync } from 'node:fs';

const D = 'https://plasticscalc.com';
const nav = `<header class="site-header"><div class="wrap top"><a class="brand" href="/"><span class="brand-mark" aria-hidden="true">PC</span><span class="brand-type"><strong>PlasticsCalc</strong><small>Engineering reference desk</small></span></a><nav class="nav" aria-label="Primary"><a href="/tools/">Tool index</a><a href="/tools/injection-molding/">Injection molding</a><a href="/tools/materials/">Materials</a><a href="/guides/">Field guides</a><a href="/about.html">Method</a><a href="/contact.html">Contact</a></nav></div></header>`;
const foot = `<footer class="site-footer"><div class="wrap"><div><strong>PlasticsCalc</strong><p>Injection molding calculators and reference notes for first-pass engineering work.</p></div><div><p><a href="/contact.html">Contact</a> &middot; <a href="/privacy.html">Privacy</a> &middot; <a href="/disclaimer.html">Engineering disclaimer</a> &middot; <a href="/about.html">Method</a></p><p class="small">&copy; 2026 PlasticsCalc &mdash; estimates require material, mold, machine, and process validation.</p></div></div></footer>`;
const esc = value => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');
const page = ({ path, title, description, h1, body, type = 'WebPage' }) => writeFileSync(path, `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${D}/${path}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website"><meta property="og:url" content="${D}/${path}"><link rel="icon" href="/assets/icons/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/css/site.css?v=20260718-width-1"><script type="application/ld+json">{"@context":"https://schema.org","@type":"${type}","name":"${esc(h1)}","url":"${D}/${path}"}</script><script defer src="/assets/js/site.js"></script><script defer src="/assets/js/calculators.js"></script><script defer src="/assets/js/phase3-calculators.js"></script></head><body>${nav}<main><div class="wrap crumb"><a href="/">Home</a> / <a href="/tools/">Tools</a> / ${esc(h1)}</div>${body}</main>${foot}</body></html>`);

const sourceLinks = {
  runner: '<a href="https://help.autodesk.com/cloudhelp/2025/ENU/MoldflowInsight-CLC-Modelprep/files/Feed-system/Runners/Runner-properties/MoldflowInsight_CLC_Modelprep_Feed_system_Runners_Runner_properties_Designing_the_runner_layout_html.html">Autodesk: runner layout</a>',
  machine: '<a href="https://stockmachines.engelglobal.com/en/us/products/buy-injection-moulding-machine-from-stock/details/t-win-8500-7000-ul/datasheet.html">ENGEL: machine data example</a>',
  cooling: '<a href="https://download.basf.com/p1/8a8082587fd4b608017fd634c46521c7/en/Estimating_Cooling_Times_in_Injection_Molding">BASF: estimating cooling times</a>',
  regrind: '<a href="https://download.basf.com/p1/8a8081c57fd4b609017fdf6cfd252296/en/Ultradur%25C2%25AE_Product_Brochure">BASF Ultradur processing notes</a>',
  cycle: '<a href="https://www.arburg.com/en/us/smart-manufacturing/reduce-cycle-time/">ARBURG: cycle-time optimisation</a>'
};

const tools = [
  ['runner-volume','Runner Volume Calculator','Cold-runner volume from circular runner diameter and total centerline length.','Mold geometry','Volume = pi x diameter squared / 4 x length.','Use CAD runner centerlines and the actual circular section; runner geometry affects material use and pressure loss.','A 6 mm runner over 800 mm has 22.62 cm3 volume.','Runner shape, taper, gates, and hot-runner manifolds need their own geometry.','runner'],
  ['runner-weight','Runner Weight Calculator','Cold-runner mass from runner volume and the stated material density.','Materials','Runner mass = runner volume x density.','Use a solid-density value for a cooled runner mass estimate, or weigh a stable runner sample.','22.62 cm3 x 1.05 g/cm3 = 23.75 g.','Do not use a finished-part density for a barrel-volume comparison.','runner'],
  ['sprue-volume','Sprue Volume Calculator','Estimate the volume of a tapered circular sprue as a frustum.','Mold geometry','Volume = pi x height x (D1 squared + D1 x D2 + D2 squared) / 12.','Take start and end diameters from the CAD sprue geometry, not a nominal nozzle label.','A 70 mm sprue from 12 mm to 6 mm is 5.50 cm3.','This is only the tapered sprue; add runners and gates separately.','runner'],
  ['screw-stroke','Screw Stroke Calculator','Convert a documented shot volume to an ideal screw-forward stroke.','Injection unit','Stroke = shot volume / screw cross-sectional area.','Use the machine maker screw diameter and a volume on the same material/process basis.','220 cm3 with a 50 mm screw gives 112.05 mm ideal stroke.','Check non-return valve, cushion, and machine stroke limits separately.','machine'],
  ['injection-unit-utilization','Injection Unit Utilization Calculator','Compare a planned shot volume with a documented usable injection-unit volume.','Injection unit','Utilization = planned shot volume / usable injection volume x 100.','Use actual shot volume and the machine maker volume definition; retain the resin and temperature basis.','180 cm3 / 240 cm3 = 75%.','A percentage is a screening value, not a machine-selection approval.','machine'],
  ['residence-time','Residence Time Calculator','Estimate barrel residence time from barrel melt mass, shot mass, and cycle time.','Injection unit','Residence time = barrel mass / (shot mass x cycles per minute).','Use a documented barrel mass at operating conditions and the complete shot, including runner where applicable.','1.2 kg with a 180 g shot every 30 s gives 3.33 min.','Actual residence-time distribution, screw design, and material stability require supplier and machine review.','machine'],
  ['screw-recovery-time','Screw Recovery Time Calculator','Estimate recovery time from shot volume and measured plasticizing rate.','Process','Recovery time = shot volume / plasticizing rate.','Use a rate measured for the exact resin, back pressure, screw speed, and melt condition.','180 cm3 / 24 cm3/s = 7.5 s.','Do not substitute a catalogue maximum rate for a validated process rate.','cycle'],
  ['fill-time','Fill Time Calculator','Estimate cavity fill time from total cavity volume and volumetric injection rate.','Process','Fill time = total cavity volume / volumetric injection rate.','Use the complete cavity volume and the programmed/measured volumetric rate, not hydraulic pressure.','96 cm3 / 40 cm3/s = 2.4 s.','Gate freeze, compressibility, pressure limits, and flow balance require process validation.','runner'],
  ['injection-rate','Injection Rate Calculator','Calculate average volumetric injection rate from shot volume and fill time.','Process','Injection rate = injected volume / fill time.','Use the actual fill-stage volume and timer boundary; state whether runner volume is included.','100 cm3 / 2.5 s = 40 cm3/s.','An average rate does not describe the programmed velocity profile or shear history.','runner'],
  ['platen-fit','Platen Fit Calculator','Screen a mold footprint against machine platen dimensions, including rotation.','Machine fit','Occupancy = larger mold-side ratio to platen x 100.','Use machine maker mounting-platen dimensions and the mold drawing’s mounting footprint.','A 700 x 600 mm mold on an 800 x 700 mm platen uses 87.5% of the limiting side.','Check bolt pattern, overhang rules, mold weight, and tie-bar clearance separately.','machine'],
  ['tie-bar-clearance','Tie-Bar Clearance Calculator','Check the remaining width and height clearance inside a four-tie-bar opening.','Machine fit','Clearance = tie-bar opening minus mold envelope.','Use the machine’s published tie-bar spacing, not the platen size; allow for handling and installed components.','An 800 x 700 mm mold in a 900 x 800 mm opening leaves 100 mm each way.','Tie-bar-less machines and core pulls need their own equipment review.','machine'],
  ['mold-height-fit','Mold Height Compatibility Calculator','Check whether a mold height lies inside the machine’s stated height range.','Machine fit','Margin = min(mold height - minimum, maximum - mold height).','Use the complete shut-height mold stack and the machine’s min/max mold-height specification.','A 450 mm mold in a 300–600 mm range has 150 mm limiting margin.','Daylight, ejector coupling, platen travel, and installation clearances are separate checks.','machine'],
  ['parts-per-shift','Parts Per Shift Calculator','Estimate good parts per shift from cycle time, cavities, uptime, and scrap rate.','Production','Good output = available seconds / cycle x cavities x uptime x yield.','Use the actual paid/run time definition and a stable, comparable scrap rule.','480 min, 30 s, four cavities, 90% uptime, 3% scrap = 3,352 good parts.','Do not use this as a staffing or delivery commitment without validated downtime data.','cycle'],
  ['oee-capacity','OEE Capacity Calculator','Estimate good-part capacity using availability, performance, quality, cycle, and cavities.','Production','Good output = ideal cycles x availability x performance x quality x cavities.','Use clearly defined OEE factors from the same time window and an agreed ideal cycle.','480 min, 30 s, four cavities, 85% availability, 95% performance, 97% quality = 3,165 parts.','OEE definitions vary by site; retain the loss-accounting rule with the result.','cycle'],
  ['scrap-adjusted-output','Scrap-Adjusted Output Calculator','Convert gross molded output and scrap rate into expected good output.','Quality','Good output = gross output x (1 - scrap rate).','Use gross and scrap values measured over the same production population.','10,000 gross parts at 3% scrap = 9,700 good parts.','This does not diagnose a defect mechanism or account for rework policy.','cycle'],
  ['regrind-blend','Regrind Blend Calculator','Calculate virgin and regrind mass for a planned blend percentage.','Materials','Regrind mass = total blend mass x regrind percentage.','Use the exact grade, moisture condition, and an approved regrind limit from the supplier/specification.','500 kg at 20% regrind = 100 kg regrind and 400 kg virgin.','Never infer an allowable percentage from this arithmetic.','regrind'],
  ['masterbatch-dosage','Masterbatch Dosage Calculator','Calculate masterbatch mass from base-resin mass and a supplier-specified dosage.','Materials','Masterbatch mass = base resin mass x dosage percentage.','Use the masterbatch supplier’s compatible grade and dosage instruction, including whether the percentage is on let-down or total blend.','200 kg base resin at 2% dosage = 4 kg masterbatch.','Colour strength and additive performance require supplier validation and trials.','regrind'],
  ['resin-purchase-quantity','Resin Purchase Quantity Calculator','Estimate virgin resin purchase mass and package count for a production order.','Materials','Purchase mass = good parts x allocated resin mass x (1 + unrecovered scrap).','Use weighed part/runner mass, cavity allocation, loss policy, and a real package size.','100,000 parts x 52 g x 3% loss = 5,356 kg, or 215 bags of 25 kg.','Inventory, purge, recycle policy, and supplier minimums are outside the estimate.','regrind'],
  ['machine-cost-per-part','Machine Cost Per Part Calculator','Allocate machine-hour cost to one molded part using cycle, cavities, and uptime.','Costing','Machine cost = hourly rate x cycle / 3,600 / cavities / uptime.','Use an internal approved machine-hour rate and the same uptime definition used in capacity planning.','A $60/h machine, 30 s cycle, four cavities, 90% uptime gives $0.14 per part.','This excludes material, labor, tooling, quality, and overhead unless your rate includes them.','cycle'],
  ['break-even-volume','Break-Even Volume Calculator','Calculate the sales volume needed to recover a fixed tooling investment.','Costing','Break-even volume = fixed tooling cost / contribution per part.','Use a real fixed-cost scope, selling price, and variable cost on the same commercial basis.','A $80,000 tool with $1.20 contribution per part breaks even at 66,667 parts.','Taxes, cash timing, quality claims, freight, and price changes are not included.','cycle']
];

const guideData = [
  ['machine-sizing-workflow','How to Size an Injection Molding Machine','A documented workflow for checking clamp force, shot capacity, mold fit, and process limits before machine selection.','Start with mold geometry and complete shot definition, then check clamp force, usable injection volume, screw stroke, platen/tie-bar fit, mold height, ejection, and automation. A press that passes one calculation may fail another screen.','Use manufacturer data for the specific machine configuration; published tie-bar spacing, platen size, clamp force, injection capacity, and mold-height ranges are separate limits.','Run <a href="/tools/injection-molding/clamp-tonnage.html">Clamp Tonnage</a>, <a href="/tools/injection-molding/injection-unit-utilization.html">Injection Unit Utilization</a>, and <a href="/tools/injection-molding/platen-fit.html">Platen Fit</a> from one documented mold/machine record.','machine'],
  ['runner-and-sprue-material-implications','Runner vs Hot Runner: Material and Process Implications','How cold runners, sprues, hot runners, and material accounting change a molding estimate.','A cold runner adds solidified material to each shot and to the material-accounting record. A hot runner can reduce cold-runner scrap but does not remove the need to document shot, cushion, residence behavior, and temperature control.','Runner geometry affects material use, pressure drop, thermal history, and balance; it is not merely a cost input.','Use <a href="/tools/injection-molding/runner-volume.html">Runner Volume</a>, <a href="/tools/injection-molding/sprue-volume.html">Sprue Volume</a>, and <a href="/tools/injection-molding/material-cost.html">Material Cost</a> as separate accounting steps.','runner'],
  ['material-usage-for-molding-production','How to Calculate Material Usage for Molding Production','A practical order-planning path from part mass to virgin-resin purchasing.','Define the good-part demand, allocated part and runner mass, expected unrecovered loss, allowable regrind, and package basis. Keep runner recovery and startup purge separate from routine scrap.','A purchase estimate is only as defensible as the mass source and material-accounting policy behind it.','Start with <a href="/tools/injection-molding/resin-weight.html">Resin Weight</a>, then use <a href="/tools/injection-molding/resin-purchase-quantity.html">Resin Purchase Quantity</a> and <a href="/tools/injection-molding/regrind-blend.html">Regrind Blend</a>.','regrind'],
  ['scrap-and-regrind-planning','Scrap and Regrind Planning for Injection Molding','How to separate yield arithmetic from material qualification when using regrind.','Measure good output, reject output, runner recovery, and purge independently. Then apply only the grade- and specification-approved regrind percentage to a defined blend.','Supplier processing guidance shows that regrind must be clean, appropriately dried, and limited by grade and quality requirements.','Connect <a href="/tools/injection-molding/scrap-rate.html">Scrap Rate</a>, <a href="/tools/injection-molding/regrind-blend.html">Regrind Blend</a>, and <a href="/tools/injection-molding/masterbatch-dosage.html">Masterbatch Dosage</a>.','regrind'],
  ['mold-fit-checks','Machine Platen, Tie-Bar, and Mold-Height Fit Checks','A sequence for screening the physical fit of an injection mold before a press is selected.','Check mounting footprint against platen, mold envelope against tie-bar opening, mold height against the published range, then review daylight, ejector interface, bolting, weight, and access.','Platen size is not tie-bar clearance; both are machine-specific published dimensions and neither replaces installation review.','Use <a href="/tools/injection-molding/platen-fit.html">Platen Fit</a>, <a href="/tools/injection-molding/tie-bar-clearance.html">Tie-Bar Clearance</a>, and <a href="/tools/injection-molding/mold-height-fit.html">Mold Height Compatibility</a>.','machine'],
  ['solid-vs-melt-density','Solid Density vs Melt Density in Molding Calculations','Why part-mass and barrel-volume calculations must keep their density basis separate.','Solid density connects finished-part volume to mass. Melt density belongs to a stated molten processing condition when comparing shot mass with injection-unit volume. Filled grades, moisture, temperature, and test basis matter.','Do not transfer a material-hub solid-density example into a melt-volume calculation without a documented melt-density basis.','Use <a href="/tools/injection-molding/resin-weight.html">Resin Weight</a> for finished-part mass and <a href="/tools/injection-molding/shot-volume.html">Shot Volume</a> for a documented melt-density conversion.','regrind'],
  ['resin-datasheets-for-calculations','How to Read Resin Datasheets for Molding Calculations','A source-selection guide for density, shrinkage, thermal data, regrind, and processing limits.','Record the exact grade, filler level, condition, temperature, test method, and whether the data is solid-state, melt-state, directional, or a supplier processing recommendation.','A generic polymer-family number is not an engineering substitute for the specified grade and condition.','Use the <a href="/tools/materials/">Materials workflow</a> before entering density, shrinkage, or cooling inputs into a calculator.','regrind'],
  ['calculator-common-mistakes','Common Mistakes When Using Injection Molding Calculators','The assumptions that most often make a quick molding estimate misleading.','Common failures include using part footprint instead of projected area, comparing a PS shot rating as if it were material-neutral, mixing solid and melt density, omitting runner/cushion, and using unmatched time windows for output or scrap.','A calculator should preserve the input source and definition so a second engineer can reproduce the estimate.','Cross-check <a href="/tools/injection-molding/shot-size.html">Shot Size</a>, <a href="/tools/injection-molding/cycle-time.html">Cycle Time</a>, and <a href="/tools/injection-molding/material-cost.html">Material Cost</a> with their related guides.','cycle'],
  ['cycle-time-workflow','How to Estimate Injection Molding Cycle Time','A practical sequence for separating cooling, motion, recovery, and loss assumptions in a cycle estimate.','Start from a stable recorded cycle, then separate fill, hold, cooling, open/eject/close, and screw recovery. Use a cooling model as a screen, not a substitute for ejection, warpage, quality, or automation validation.','Cycle improvement changes capacity only when the limiting operation and quality boundary are retained.','Use <a href="/tools/injection-molding/cooling-time.html">Cooling Time</a>, <a href="/tools/injection-molding/screw-recovery-time.html">Screw Recovery Time</a>, <a href="/tools/injection-molding/parts-per-shift.html">Parts Per Shift</a>, and <a href="/tools/injection-molding/machine-cost-per-part.html">Machine Cost Per Part</a>.','cooling']
];

for (const [id, name, description, group, formula, input, example, limitation, source] of tools) {
  const related = tools.filter(t => t[3] === group && t[0] !== id).slice(0, 3).map(t => `<a href="/tools/injection-molding/${t[0]}.html">${t[1]}</a>`).join(' &middot; ');
  page({path:`tools/injection-molding/${id}.html`, title:`${name} | PlasticsCalc`, description, h1:name, type:'SoftwareApplication', body:`<section class="hero"><div class="wrap"><p class="eyebrow">Injection molding · ${group}</p><h1>${name}</h1><p class="lead">${description} Use this as a documented planning estimate, then validate it against the actual machine, mold, resin, and process.</p></div></section><section class="wrap section"><div class="calculator" data-calculator="${id}"></div><div class="calc-reference-grid"><section class="reference-block reference-method"><h2>Formula and method</h2><p class="formula">${formula}</p><p>${input}</p></section><section class="reference-block reference-inputs"><h2>Inputs and units</h2><p>Use controlled records, CAD, measured production data, the exact resin data sheet, or machine-maker specifications. Keep the material and time basis with the result.</p></section><section class="reference-block reference-example"><h2>Worked example</h2><p>${example}</p></section></div><div class="calc-decision-grid"><section class="decision-block"><h2>What the result supports</h2><p>This result is a first-pass screen for ${group.toLowerCase()} planning. Use it to identify the next record or engineering check, not as a release decision.</p></section><section class="decision-block decision-caution"><h2>Sanity check</h2><p>Check the unit basis and whether all quantities describe the same cavity, shot, machine, or production window before comparing values.</p></section><section class="decision-block decision-limits"><h2>Important limitation</h2><p>${limitation}</p><p>Reference: ${sourceLinks[source]}.</p></section><section class="decision-block"><h2>Next calculation</h2><p>${related || '<a href="/tools/injection-molding/">Browse related injection molding tools</a>'}</p></section></div><div class="calc-bottom-grid"><section class="bottom-block bottom-faq"><h2>FAQ</h2><h3>What must be checked after using ${name.toLowerCase()}?</h3><p>Retain the input source and compare this estimate with the applicable machine, mold, supplier, or production record before relying on it.</p></section><section class="bottom-block bottom-related"><h2>Related workflow</h2><p><a href="/guides/">Read the field guides</a> &middot; <a href="/tools/injection-molding/">Return to injection molding tools</a></p></section></div></section>`});
}

for (const [id, name, description, body, sourceAdvice, links, source] of guideData) {
  page({path:`guides/${id}.html`, title:`${name} | PlasticsCalc`, description, h1:name, body:`<section class="hero"><div class="wrap"><p class="eyebrow">Injection molding guide</p><h1>${name}</h1><p class="lead">${description}</p></div></section><article class="wrap section"><section class="guide-reading"><h2>The engineering question</h2><p>${body}</p><h2>What to document</h2><p>${sourceAdvice}</p><h2>Practical workflow</h2><p>${links}</p><h2>Validation boundary</h2><p>Use manufacturer documentation, grade-specific supplier data, controlled process records, and trials for any equipment, quality, material, or commercial commitment. A static calculator is a transparent starting point, not a simulation or approval.</p><h2>Reference</h2><p>${sourceLinks[source]}</p></section></article>`});
}

const toolCards = tools.map(t => `<article class="card"><p class="eyebrow">${t[3]}</p><h3><a href="/tools/injection-molding/${t[0]}.html">${t[1]}</a></h3><p>${t[2]}</p></article>`).join('');
const guideCards = guideData.map(g => `<article class="card"><h2><a href="/guides/${g[0]}.html">${g[1]}</a></h2><p>${g[2]}</p></article>`).join('');
for (const target of ['tools/index.html','tools/injection-molding/index.html']) {
  let html = readFileSync(target, 'utf8');
  html = html.replace('</main>', `<section class="wrap section"><p class="eyebrow">Phase 3 reference tools</p><h2>More documented injection-molding checks</h2><div class="grid">${toolCards}</div></section></main>`);
  writeFileSync(target, html);
}
let home = readFileSync('index.html', 'utf8');
home = home.replace('</main>', `<section class="wrap section"><p class="eyebrow">Expanded workflow checks</p><h2>Move from geometry to machine fit, output, and material planning</h2><div class="grid"><article class="card"><h3><a href="/tools/injection-molding/runner-volume.html">Cold-runner and sprue accounting</a></h3><p>Document feed-system volume and mass before comparing the complete shot or material cost.</p></article><article class="card"><h3><a href="/guides/machine-sizing-workflow.html">Machine sizing workflow</a></h3><p>Screen clamp, injection unit, platen, tie-bar, and mold-height limits as separate checks.</p></article><article class="card"><h3><a href="/guides/material-usage-for-molding-production.html">Material planning workflow</a></h3><p>Carry part mass, recovery policy, regrind approval, and purchase packaging into one traceable plan.</p></article></div></section></main>`);
writeFileSync('index.html', home);
let guideHub = readFileSync('guides/index.html', 'utf8');
guideHub = guideHub.replace('</main>', `<section class="wrap section"><p class="eyebrow">Phase 3 field guides</p><h2>Workflows beyond a single calculator</h2><div class="grid">${guideCards}</div></section></main>`);
writeFileSync('guides/index.html', guideHub);
let materialHub = readFileSync('tools/materials/index.html', 'utf8');
materialHub = materialHub.replace('</main>', `<section class="wrap section"><p class="eyebrow">Material planning tools</p><h2>Use grade-specific data in a documented blend and purchase workflow</h2><div class="grid"><article class="card"><h3><a href="/tools/injection-molding/regrind-blend.html">Regrind Blend Calculator</a></h3><p>Convert an approved blend percentage into virgin and regrind mass.</p></article><article class="card"><h3><a href="/tools/injection-molding/masterbatch-dosage.html">Masterbatch Dosage Calculator</a></h3><p>Apply a supplier-specified dosage to a stated base-resin mass.</p></article><article class="card"><h3><a href="/tools/injection-molding/resin-purchase-quantity.html">Resin Purchase Quantity Calculator</a></h3><p>Plan virgin material and package count from documented mass and loss assumptions.</p></article><article class="card"><h3><a href="/guides/resin-datasheets-for-calculations.html">Resin datasheet guide</a></h3><p>Choose a grade, condition, test basis, and temperature context before calculating.</p></article></div></section></main>`);
writeFileSync('tools/materials/index.html', materialHub);

const phase3Paths = new Set([...tools.map(t => `/tools/injection-molding/${t[0]}.html`), ...guideData.map(g => `/guides/${g[0]}.html`)]);
const sitemap = readFileSync('sitemap.xml', 'utf8').replace(/\s*<url><loc>([^<]+)<\/loc><\/url>/g, (entry, url) => phase3Paths.has(url.replace(D, '')) ? '' : entry);
const urls = [...phase3Paths].map(path => `  <url><loc>${D}${path}</loc></url>`).join('\n');
writeFileSync('sitemap.xml', sitemap.replace('</urlset>', `\n${urls}\n</urlset>`));
